server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/songll/spring-cloud-config.git   # Gitee上的git仓库名字
          # 搜索目录
          search-paths:
            - spring-cloud-config
          force-pull: true
          username: 498705469@qq.com
          password: xusong123
      # 读取分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka