server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh             # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001    # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**      # 断言，路径匹配的进行路由

        - id: payment_routh2            # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001    # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**       # 断言，路径匹配的进行路由
            #- After=2020-11-10T19:08:33.512+08:00[Asia/Shanghai]
            #- Before=2020-11-10T19:08:33.512+08:00[Asia/Shanghai]
            #- Between=2020-11-10T19:08:33.512+08:00[Asia/Shanghai],2020-11-11T19:08:33.512+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id,\d+
            #- Host=**.baidu.com
            #- Method=GET
            #- Query=username, \d+

eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527
    prefer-ip-address: true   # 访问路径可以显示IP地址
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka
