server:
  port: 8007

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    # 表示是否将自己注册进Eureka Server, 默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息, 默认为true. 单节点无所谓, 集群必须设置为true才能配和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 设置与 Eureka Server 交互的地址查询服务和注册中心服务都需要依赖这个地址
      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/    # 集群版
  instance:
    instance-id: payment-hystrix-8007
    prefer-ip-address: true   # 访问路径可以显示IP地址